name: Publish project to Maven repository
on:
  push:
    branches-ignore: 
      - javadoc
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: '[{"id": "snapshots", "username": "${{ secrets.MAVEN_NAME }}", "password": "${{ secrets.MAVEN_TOKEN }}"}]'
      - name: Deploy with Maven
        run: mvn deploy
